# environment.yml

# Use followingsto create new virtual env if using conda:
#  conda env create -f environment.yml
#  conda activate vlm-cc


name: vlm-cc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - opencv
  - pillow
  - tqdm
  - requests
  - rdflib
  - python-dotenv
  - pip:
      - ollama
      - openai
      - open3d==0.18.0
